### ISSUE TITLE
Create Icon

### ISSUE THREAD

**Issue by PotatoFi** [noiob/pulse-alert#1]
Thanks for including me on this project! There's a few considerations to keep in mind on this one:

1. We've got 25x25px to work with... not much.
2. Since this app is obviously only going to be for the Pebble 2, we have black-and-white only, so no greys for dithering, which limits us even more.

It seems like the Pebble "heart" icon would really make sense here, so here are a couple of very early ideas/drafts:

![pules alert 1](https://cloud.githubusercontent.com/assets/19558338/21559399/edd0576c-ce08-11e6-96d8-0e3112379b88.png)

Obviously this one would need some work.

![pulse alert 2](https://cloud.githubusercontent.com/assets/19558338/21559400/f053d45a-ce08-11e6-9746-3efb592f3c31.png)

...but, since the bit-depth on these images will be one, they'll really be more like this:

![pulse1converted](https://cloud.githubusercontent.com/assets/19558338/21559444/8fadd1f4-ce09-11e6-967d-e7d9110ff88e.png)

![pulse2converted](https://cloud.githubusercontent.com/assets/19558338/21559446/9245a086-ce09-11e6-8c32-e82295a42c8e.png)

Clearly, there's a lot of pixel cleanup there to be done once we settle on the design. Let me know what you think so far, and if you have any ideas!

**Comment by noiob** [comment]
I really like both of them, but I'm more for the exclamation mark, if if can be done visibly enough

I was thinking of including the heart icon in the app anyways (it's prettier than writing "HR" all the time) and the exclamation mark could be used as an indicator that the current HR is greater than the threshold (probably should make a "clean UI" issue for that). So, thinking about that, I'd probably choose the exclamation mark one.

Hovever, I don't know if it's my screen resolution or sth, but it's very easy to read as "heart with vertical line in it" to me. Maybe something similar to [this emoji](http://emojipedia.org/heavy-heart-exclamation-mark-ornament/) (❣) would be easier to see? It'd probably be harder to interpret as "attention" and more as a bleeding heart or sth.

**Comment by noiob** [comment]
After the UI rework I don't think I want to include a heart + exclamation mark in it (the heart I added is very small), but I find myself even more in favor of the *Heavy Heart Exclamation Mark Ornament* as an app icon for some reason

**Comment by PotatoFi** [comment]
I see this process as highly iterative, so lemme know what you think and we'll move on to then next step.

1: ![1](https://cloud.githubusercontent.com/assets/19558338/21597793/b500ff38-d10d-11e6-954e-46d829931766.png)

2: ![2](https://cloud.githubusercontent.com/assets/19558338/21597794/b6e0a538-d10d-11e6-850e-d703b1ac7a3e.png)

3: ![3](https://cloud.githubusercontent.com/assets/19558338/21597795/ba71af62-d10d-11e6-9d26-98f5797f581a.png)

4: ![4](https://cloud.githubusercontent.com/assets/19558338/21597814/21b068c6-d10e-11e6-9822-fe94e1c7d94f.png)

5: ![5](https://cloud.githubusercontent.com/assets/19558338/21597845/3e41106c-d10e-11e6-935c-03a07d5e7dc5.png)

6: ![6](https://cloud.githubusercontent.com/assets/19558338/21597868/be1a77b0-d10e-11e6-92d4-a874debf9617.png) - This one is weird because I've "cleaned up" the pixels on the dot. The same treatment will probably need to be applied to any of the other icons we use, since we're working with a black and white (not greyscale) display.


I've also got some concerns about what these icons will do on the Pebble 2 screen, since it's black and white. I've got a Pebble Classic, but no Pebble 2 (yet!) to test on, so you'll have to let me know what happens on-watch. On the Pebble Classic, there's no "white", so the colors just invert.

**Comment by noiob** [comment]
I guess I like 3 best, because it's the one that conveys the exclamation mark shape best. 6 is a close second, even with the filled dot.

I have one app I've done a png icon for (I just checked, it even has both white and transparent for some reason) and it inverts just fine.

**Comment by PotatoFi** [comment]
Ok, here they are. I'm very curious to see what the 25x25 icon does on the black and white screen. I'm fully expecting to at least edit it pixel-by-pixel to clean it up. Lemme know how it goes!

![25x25 pulse alert](https://cloud.githubusercontent.com/assets/19558338/21598442/39ec2072-d11a-11e6-89a7-fde1054b093b.png)

![48x48 pulse alert](https://cloud.githubusercontent.com/assets/19558338/21598444/3cf7e3f0-d11a-11e6-81fe-24eed2de5800.png)

![144x144 pulse alert](https://cloud.githubusercontent.com/assets/19558338/21598451/5a2548b4-d11a-11e6-802f-7731d8e34b9c.png)

**Comment by noiob** [comment]
It works! The tip of the heart is a bit too thin, otherwise it's great! ![img_1516](https://cloud.githubusercontent.com/assets/8197071/21598577/41fe1352-d15f-11e6-914e-e9554a701c9e.JPG)

**Comment by noiob** [comment]
Here's screenshots of it both highlighted and not, if it helps
![pebble_screenshot_2017-01-03_02-55-23](https://cloud.githubusercontent.com/assets/8197071/21598636/314d040e-d160-11e6-843d-a0ac49420cf0.png) ![pebble_screenshot_2017-01-03_02-55-31](https://cloud.githubusercontent.com/assets/8197071/21598637/316e48f8-d160-11e6-8bd5-9ed4baca3823.png)

**Comment by PotatoFi** [comment]
Ok, I think the solution here is to do a pixel-by-pixel edit to clean it up, instead of a straight export from vectorized image. Gimmeh some time, we'll make it mo' better!

Also: I'm keeping an eye out for a deal on a white Pebble 2. I want one! ;)

**Comment by noiob** [comment]
I'm gonna go sleep now, so no rush. Thanks a lot!

**Comment by PotatoFi** [comment]
Give this one a try when you wake up. :)

![25x25 pulse alert bw](https://cloud.githubusercontent.com/assets/19558338/21598704/8b0f17da-d11e-11e6-9172-ac9ad05a7b1e.png)

Or this slightly different interpretation:

![25x25 pulse alert bw 2](https://cloud.githubusercontent.com/assets/19558338/21598716/b1b71ba8-d11e-11e6-93ee-4d344d11b7a3.png)

**Comment by noiob** [comment]
Awesome! I chose the second one. Closing this issue with the next commit. How should I refer to you when giving credit? I'd write a name (with a link if you wanna) in the Readme, App description (w/o link) and Settings page.

I do recommend the white P2. Thanks again!

**Comment by PotatoFi** [comment]
Attribution is not required, but if you'd like to, you can attribute it to Joel Crane. A link could be: https://twitter.com/Potato_Fi

Again, not required.

When I get my Pebble 2 I'll be sure to get this app, it looks great! Be sure to hit me up if you decide to create any new apps. :)
