### ISSUE TITLE
Current UI is very ugly and not very functional

### ISSUE THREAD

**Issue by noiob** [noiob/pulse-alert#2]
This is just a thread to collect all the UI ideas. The current UI is very basic because I haven't thought about it much. So here's what I've been thinking about:

### Add a heart rate graph
This depends on how much past data I'd be able to actually get from Health, but I suppose something like the graph in [HR+](https://apps.getpebble.com/en_US/application/5829095036ac5a063000016f) would be pretty helpful (maybe with the high/low values written next to it to give a sense of scale)

### Add the heart icon (as an indicator)?
@PotatoFi has agreed to make an icon for Pulse Alert (see #1). One of the drafts looks like this: ![](https://cloud.githubusercontent.com/assets/19558338/21559400/f053d45a-ce08-11e6-9746-3efb592f3c31.png)
I was thinking about adding the typical Pebble heart icon anyways, and was thinking of using the exclamation mark as an indicator of wether or not the current HR is higher than the threshold value.

### More buttons!
The current control scheme is just me slapping buttons on the actionbar to make stuff work. Here's what I have in mind for the future:
- **mute:** Mutes the alert for a set time (might be useful when starting a sports activity or something) *Icon:* 💤
- **set threshold:** To use less buttons, this should be two presses rather than one (pushing this brings up the existing plus/minus buttons and one to accept the value) *Icon:* ✏️
- **dis/enable background worker:** Probably hidden in a menu or sth, but I find it crucial to be able to control wether the background task is running or not. It's possible to change that in the OS settings, but it's not very obvious. A menu could also contain further functionality. *Icon:* ⚙

**Comment by noiob** [comment]
Reworked the UI to look like this:
![pebble_screenshot_2016-12-31_19-50-04](https://cloud.githubusercontent.com/assets/8197071/21578887/b0707c4a-cf92-11e6-9dab-c81961af0fb6.png)

(the gear and snooze buttons are not functional for now)

**Comment by noiob** [comment]
The Graph works! and it doesn't slow down the UI too much, so I guess this is done. I'm not doing the Icon thing because the heart is way too small anyways and it wouldn't add any information (you can see which number is bigger anyways)

![pebble_screenshot_2017-01-02_16-58-34](https://cloud.githubusercontent.com/assets/8197071/21594237/8454fe9e-d120-11e6-9f0a-a3aa8ddabea3.png)

**Comment by PotatoFi** [comment]
If you'd like, I can probably draw you a "heart" icon that works better pixel-by-pixel (unless you've removed it).

**Comment by noiob** [comment]
The one in the assets is still in the app, and it's a shitty downscale of the one on the HR screen. I'd be super thankful for a good version!

**Comment by PotatoFi** [comment]
What exact resolution do you need in pixels?

**Comment by noiob** [comment]
This is it: [heart.png](https://github.com/noiob/pulse-alert/blob/master/resources/images/heart.png)
It's 24x23 though you can make it 24x24 or 23x23

**Comment by PotatoFi** [comment]
![23x23 pulse alert](https://cloud.githubusercontent.com/assets/19558338/21598465/b579929c-d11a-11e6-9783-c2725d7a464e.png)

Let's see how that one works. Still unsure about what will happen when we convert that to pure black-and-white... it might not look good.

**Comment by noiob** [comment]
Here's how it looks on the watch. I had to remove the alpha for it to not be black, could've propably worked in code, idk. Same issue as with the icon, but it already looks so much cleaner 😊
![pebble_screenshot_2017-01-03_02-52-04](https://cloud.githubusercontent.com/assets/8197071/21598615/d2d3405a-d15f-11e6-8c57-6283b63b7274.png)

**Comment by PotatoFi** [comment]
Let's give this one a try.

![23x23 pulse alert ui](https://cloud.githubusercontent.com/assets/19558338/21598795/f7bdb9da-d11f-11e6-8d16-b920b82764c8.png)

**Comment by noiob** [comment]
This one's sharp as a blade. Thank you!
